repos:
  - repo: https://github.com/prettier/prettier
    rev: "master"
    hooks:
      - id: prettier
  - repo: https://github.com/python/black
    rev: ae5588cf073be10b51dc48ad2fc513e11c4f3e03
    hooks:
      - id: black
        args: [-l 79]
  - repo: https://github.com/thg-consulting/whithercanada
    rev: 1dc71abeafc8bfdeb80b1ed820d408c12e06c04a
    hooks:
      - id: check_commit_message
        stages: [prepare-commit-msg]
